name: Latest DIO Articles
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with DIO posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
        
      - name: Pull in DIO posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://web.dio.me/articles/rss/vitoriadelimaboin"
          max_post_count: 3
          template: "$newline- [ $title ]($url)"
          retry_count: 1
